version: '3.8'
services:
  database:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    ports: 
      - "5432:5432"